spring:

  config:
    import: "optional:configtree:/run/secrets/"

  application:
    name: PetSitter

  datasource:
    url: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${postgres-password}

  jpa:
    hibernate:
      ddl-auto: create-drop

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

springdoc:

  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
